In [98]:
import random
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [99]:
vector1 = np.array((range(1,11)), dtype=int)
print(vector1)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [100]:
matrix2 = np.zeros((3,3), dtype=float)
print(matrix2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [101]:
matrix3 = np.random.randint(1, 11, size=(5, 5))
print(matrix3)

[[10 10  7  5  3]
 [ 9  2  5  7  4]
 [ 8  6  9  3 10]
 [ 4  5  9  9  2]
 [ 1  9  6  1  9]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення

In [102]:
matrix4 = np.random.rand(4, 4)
print(matrix4)

[[0.39035374 0.81008997 0.82445526 0.38307039]
 [0.62500133 0.28669017 0.72729487 0.37524529]
 [0.36549808 0.85567571 0.65725595 0.2138191 ]
 [0.54282095 0.64330565 0.61040418 0.22839714]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [103]:
vector51 = np.array([random.randint(1,10) for k in range(5)])
vector52 = np.array([random.randint(1,10) for m in range(5)])
print("First vector:", vector51)
print("Second vector:",vector52, "\n")



sum_result = vector51 + vector52
sub_result = vector51 - vector52
mult_result = vector51 * vector52

print("Sum vector:", sum_result)
print("Sub vector:",sub_result)
print("Mul vector:",mult_result)

First vector: [6 1 6 5 7]
Second vector: [5 8 6 6 5] 

Sum vector: [11  9 12 11 12]
Sub vector: [ 1 -7  0 -1  2]
Mul vector: [30  8 36 30 35]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [104]:
vector61 = np.random.rand(1,7)
vector62 = np.random.rand(1,7)
print("First v:",vector61)
print("Second v:",vector62, "\n")

print("Dot:",vector61 * vector62)

First v: [[0.24334954 0.34609132 0.20529148 0.401012   0.8437195  0.93592225
  0.82858911]]
Second v: [[0.4817614  0.91023592 0.05265219 0.80100923 0.57061281 0.84851434
  0.42750429]] 

Dot: [[0.11723641 0.31502475 0.01080905 0.32121431 0.48143715 0.79414345
  0.3542254 ]]


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [105]:
matrix71 = np.random.randint(1, 11, size=(2, 2))
matrix72 = np.random.randint(1, 11, size=(2, 3))
dot_matrix = np.dot(matrix71,matrix72)
print("matrix_1:")
print(matrix71)
print("matrix_2:")
print(matrix72)
print("\n", "Dot matrix:")
print(dot_matrix)


matrix_1:
[[4 6]
 [3 8]]
matrix_2:
[[ 8  5 10]
 [ 3  8  5]]

 Dot matrix:
[[50 68 70]
 [48 79 70]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [106]:
matrix8 = np.random.randint(1, 11, size=(3, 3))
print(matrix8)
print("\n")
a_inv = np.linalg.inv(matrix8)
print(a_inv)

[[9 1 6]
 [8 7 2]
 [2 4 6]]


[[ 0.09189189  0.04864865 -0.10810811]
 [-0.11891892  0.11351351  0.08108108]
 [ 0.04864865 -0.09189189  0.14864865]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [107]:
matrix9 = np.random.random((4, 4))
print(matrix9)
transpose_matrix = np.transpose(matrix9)
print("\n")
print(transpose_matrix)

[[0.98025782 0.72845711 0.43180074 0.03991835]
 [0.75057238 0.36479839 0.70588562 0.51044146]
 [0.84699199 0.36203571 0.95635052 0.38314196]
 [0.94763113 0.66828641 0.17584251 0.90074023]]


[[0.98025782 0.75057238 0.84699199 0.94763113]
 [0.72845711 0.36479839 0.36203571 0.66828641]
 [0.43180074 0.70588562 0.95635052 0.17584251]
 [0.03991835 0.51044146 0.38314196 0.90074023]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [108]:
vector10 = np.random.randint(1, 11, size=4)
matrix10 = np.random.randint(1, 11, size=(3, 4))
dot_vm = np.dot (vector10, matrix10.T)
print(dot_vm)



[ 99 101 109]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [109]:
vector11 = np.random.random(size=3)
matrix11 = np.random.random(size=(2, 3))
# print(vector11)
# print(matrix11)
result = np.dot(vector11, matrix11.T)
print(result)

[0.96394522 0.90668954]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [110]:
matrix121 = np.random.randint(1,10, size=(2, 2))
matrix122 = np.random.randint(1,10, size=(2, 2))
result = matrix121 * matrix122
print(result)

[[10 10]
 [20 12]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [111]:
matrix131 = np.random.randint(1,10, size=(2, 2))
matrix132 = np.random.randint(1,10, size=(2, 2))
result = np.dot(matrix131, matrix132)
print(result)

[[11 23]
 [26 74]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [112]:
matrix14 = np.random.randint(1,100, size=(5, 5))
result = np.sum(matrix14)
print(result)

1532


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [113]:
matrix151 = np.random.randint(1,10, size=(4, 4))
matrix152 = np.random.randint(1,10, size=(4, 4))
result = matrix151 - matrix152
print(result)

[[-6 -2 -4  8]
 [-1  4  1  1]
 [ 0 -1 -1  0]
 [-3 -5  3  3]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [114]:
matrix16 = np.random.random(size=(3, 3))

result = np.sum(matrix16, axis=1)
print(result)

[0.48844817 1.51972433 1.27534819]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел. 

In [115]:
matrix17 = np.random.randint(1,100, size=(3, 4))
result = np.square(matrix17)
print(matrix17)
print(result)

[[39 75 13 37]
 [62 21 55 17]
 [38 16 53 71]]
[[1521 5625  169 1369]
 [3844  441 3025  289]
 [1444  256 2809 5041]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [116]:
vector18 = np.random.randint(1,50, size=3)
result = np.square(vector18)
print(vector18)
print(result)


[12 15 44]
[ 144  225 1936]
